services:
  python-service:
    build:
      context: ./python-service
    ports:
      - "8000:8000"
    restart: unless-stopped
  machine-simulator:
    build:
      context: ./python-machine-simulator
    ports:
      - "8001:8001"
    restart: unless-stopped
